name: PR auto merge
on:
  schedule:
    - cron: '00 13 * * *'
    
  workflow_dispatch:  
    
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          LOG: "DEBUG"
          UPDATE_LABELS: ""
